In [5]:
# Import setup
import pandas as pd

In [6]:
# Create a list containing all the files for 2022 Jersey City data
files = ['JC-202301-citibike-tripdata.csv',
         'JC-202302-citibike-tripdata.csv',
         'JC-202303-citibike-tripdata.csv',
         'JC-202304-citibike-tripdata.csv',
         'JC-202305-citibike-tripdata.csv',
         'JC-202306-citibike-tripdata.csv',
         'JC-202307-citibike-tripdata.csv',
         'JC-202308-citibike-tripdata.csv',
         'JC-202309-citibike-tripdata.csv',
         'JC-202310-citibike-tripdata.csv',
         'JC-202311-citibike-tripdata.csv',
         'JC-202312-citibike-tripdata.csv']

In [7]:
# Create an empty dataframe to store all data
citibike_df = pd.DataFrame()

In [8]:
# Loop through the list of files and concatonate all data to the dataframe
for file in files:
    data = pd.read_csv(file) 
    citibike_df = pd.concat([citibike_df, data], axis=0)

In [9]:
# Show the dataframe
citibike_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,0905B18B365C9D20,classic_bike,2023-01-28 09:18:10,2023-01-28 09:28:52,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735938,-74.030305,40.727596,-74.044247,member
1,B4F0562B05CB5404,electric_bike,2023-01-23 20:10:12,2023-01-23 20:18:27,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Southwest Park - Jackson St & Observer Hwy,HB401,40.735938,-74.030305,40.737551,-74.041664,member
2,5ABF032895F5D87E,classic_bike,2023-01-29 15:27:04,2023-01-29 15:32:38,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Marshall St & 2 St,HB408,40.735944,-74.030383,40.740802,-74.042521,member
3,E7E1F9C53976D2F9,classic_bike,2023-01-24 18:35:08,2023-01-24 18:42:13,Hoboken Terminal - Hudson St & Hudson Pl,HB101,Hamilton Park,JC009,40.735986,-74.030364,40.727596,-74.044247,member
4,323165780CA0734B,classic_bike,2023-01-21 20:44:09,2023-01-21 20:48:08,Hamilton Park,JC009,Manila & 1st,JC082,40.727596,-74.044247,40.721651,-74.042884,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
58675,7E862701EE7A6A03,classic_bike,2023-12-20 17:55:41,2023-12-20 18:00:10,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748720,-74.040487,40.754530,-74.026580,casual
58676,DFAF91AB91BE25DB,classic_bike,2023-12-13 14:36:43,2023-12-13 14:42:31,Heights Elevator,JC059,Bloomfield St & 15 St,HB203,40.748767,-74.040470,40.754530,-74.026580,member
58677,AEE7B49E6EDFAE6F,classic_bike,2023-12-18 16:40:00,2023-12-18 16:45:45,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744291,-74.034404,40.754530,-74.026580,member
58678,A38E98956AD72EFB,classic_bike,2023-12-02 13:42:51,2023-12-02 13:50:42,6 St & Grand St,HB302,Bloomfield St & 15 St,HB203,40.744398,-74.034501,40.754530,-74.026580,member
58679,F16E0B969D877368,classic_bike,2023-12-19 16:30:13,2023-12-19 16:36:54,6 St & Grand St,HB302,Clinton St & 7 St,HB303,40.744398,-74.034501,40.745420,-74.033320,member

In [11]:
# Store the dataframe as CSV file
citibike_df.to_csv('citibike2023jc_data.csv', index=False)